connect 'jdbc:derby://localhost:1527/fpx;create=true';
SHOW TABLES;
DROP TABLE USERTABLE;
DROP TABLE OPPORTUNITYTABLE;
DROP TABLE NOTIFICATIONCRITERIATABLE;
DROP TABLE NOTIFICATIONMESSAGETABLE;
DROP TABLE NOTIFICATIONMESSAGE_TABLE;