connect 'jdbc:derby://localhost:1527/fpx;create=true';
SHOW TABLES;
DESCRIBE NOTIFICATIONMESSAGETABLE;
SELECT 
CRITERIAID    
,CAST(USERNAME AS VARCHAR(18)) AS USERNAME 
,CAST(OPPORTUNITYOWNERNAME AS VARCHAR(18)) AS OWNER
,CAST(MESSAGE AS VARCHAR(60)) AS MESSAGE

 FROM NOTIFICATIONMESSAGETABLE;






