connect 'jdbc:derby://localhost:1527/fpx;create=true';
SHOW TABLES;
DESCRIBE NOTIFICATIONCRITERIATABLE;
SELECT ID,CAST(ENABLED AS VARCHAR(18)) AS Enabled,CAST(NAME AS VARCHAR(18)) AS Description,CAST(EXPRESSION AS VARCHAR(36)) AS EXPRESSION FROM NOTIFICATIONCRITERIATABLE;





