connect 'jdbc:derby://localhost:1527/fpx;create=true';
SHOW TABLES;
DESCRIBE USERTABLE;
DESCRIBE OPPORTUNITYTABLE;

SELECT CAST(ID AS VARCHAR(18)) AS ID,CAST(FIRSTNAME AS VARCHAR(20)) AS FirstName,CAST(LASTNAME AS VARCHAR(20)) AS LASTNAME,CAST(MANAGERID AS VARCHAR(18)) AS MANAGERID FROM USERTABLE;
SELECT CAST(ID AS VARCHAR(18)) AS ID,CAST(OWNERID AS VARCHAR(18)),NAME FROM OPPORTUNITYTABLE;



